<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\RepoIntel.Application\RepoIntel.Application.csproj" />
    <ProjectReference Include="..\RepoIntel.Domain\RepoIntel.Domain.csproj" />
    <ProjectReference Include="..\RepoIntel.Contracts\RepoIntel.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
    <PackageReference Include="Octokit" Version="13.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>
</Project>
